version: '{branch}-{build}-no-release'
image: Visual Studio 2017 Preview
install:
- cmd: >-
    git submodule sync

    git submodule update --recursive --init
cache:
- node_modules
- '%USERPROFILE%\.nuget\packages'
build_script:
- cmd: msbuild Build.proj /p:Configuration=Release
test_script:
- cmd: msbuild Build.proj /t:TestRegressions /p:Configuration=Release