version: '{branch}-{build}-no-release'
image: Visual Studio 2017 Preview
clone_script:
- cmd: >-
    git clone https://github.com/Microsoft/workbooks --recursive

    cd workbooks
cache:
- workbooks\node_modules
- '%USERPROFILE%\.nuget\packages'
build_script:
- cmd: msbuild Build.proj /p:Configuration=Release
test_script:
- cmd: msbuild Build.proj /t:TestRegressions /p:Configuration=Release